# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-09 20:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0002_courseinstance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_booked', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='courseinstance',
            name='spaces',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='course_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.CourseInstance'),
        ),
        migrations.AddField(
            model_name='booking',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
